api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SongViewSet, ArtistViewSet, SongSearchAPIView, SongDownloadView

router = DefaultRouter()
router.register(r'songs', SongViewSet)
router.register(r'artists', ArtistViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('search', SongSearchAPIView.as_view()),
    path('download/<int:pk>', SongDownloadView.as_view(), name='song_download'),
]

songs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from songs.views.song_view import SongView
from songs.views.download_song_view import DownloadSongView
from songs.views.player_view import PlayerView
from songs.views.song_details_view import SongDetailsView
from songs.views.random_song_view import RandomSongView
from songs.views.browse_songs_views import (
    BrowseSongsByLicenseView,
    BrowseSongsByFilenameView,
    BrowseSongsByGenreView,
    BrowseSongsByRatingView
)

urlpatterns = [
    path('', TemplateView.as_view(template_name='song_list.html'), name='songs'),
    path('<int:pk>/', SongView.as_view(), {}, 'view_song'),
    path('<int:pk>/download', DownloadSongView.as_view(), name='download_song'),
    path('<int:pk>/song_details', SongDetailsView.as_view(), {}, 'song_details'),
    path('random/', RandomSongView.as_view(), {}, 'random_song'),
    path('player/', PlayerView.as_view(), {}, 'player'),
    path('browse/license/<str:query>/', BrowseSongsByLicenseView.as_view(), name='browse_by_license'),
    path('browse/filename/<str:query>/', BrowseSongsByFilenameView.as_view(), name='browse_by_filename'),
    path('browse/genre/<str:query>/', BrowseSongsByGenreView.as_view(), name='browse_by_genre'),
    path('browse/rating/<int:query>/', BrowseSongsByRatingView.as_view(), name='browse_by_rating'),
]

interactions/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from songs.models import Song
from homepage.models import Profile

class Comment(models.Model):
    class Ratings(models.IntegerChoices):
        _1 = 1, _("1: Very poor")
        _2 = 2, _("2: Poor")
        _3 = 3, _("3: Listenable")
        _4 = 4, _("4: Good attempt")
        _5 = 5, _("5: Average")
        _6 = 6, _("6: Above average")
        _7 = 7, _("7: Enjoyable")
        _8 = 8, _("8: Very good")
        _9 = 9, _("9: Excellent")
        _10 = 10, _("10: Awesome")

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    rating = models.PositiveSmallIntegerField(choices=Ratings.choices)
    create_date = models.DateTimeField(default=timezone.now)

class ArtistComment(models.Model):
    class Meta:
        unique_together = ('profile', 'song')
        verbose_name_plural = 'artist comments'
        db_table = 'songs_artist_comments'

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    create_date = models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

class Favorite(models.Model):
    class Meta:
        unique_together = ('profile', 'song')

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)

songs/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex
from django.core.exceptions import ValidationError
from django.conf import settings

from homepage.models import Profile

class Song(models.Model):
    class Formats(models.TextChoices):
        _669 = '669', _('669: Composer 669 / UNIS 669')
        AHX = 'AHX', _('AHX: Abyss\' Highest eXperience, formerly THX')
        AMF = 'AMF', _('AMF: ASYLUM / DSMI')
        AMS = 'AMS', _('AMS: Extreme\'s Tracker / Velvet Studio')
        C67 = 'C67', _('C67: CDFM / Composer 670')
        DBM = 'DBM', _('DBM: Digi Booster Pro')
        DIGI = 'DIGI', _('DIGI: Digi Booster')
        DMF = 'DMF', _('DMF: X-Tracker')
        DSM = 'DSM', _('DSM: DSIK')
        DSYM = 'DSYM', _('DSYM: Digital Symphony')
        DTM = 'DTM', _('DTM: Digital Tracker / Digital Home Studio')
        FAR = 'FAR', _('FAR: Farandole Composer')
        FMT = 'FMT', _('FMT: FM Tracker')
        GDM = 'GDM', _('GDM: BWSB Sound System')
        HVL = 'HVL', _('HVL: HivelyTracker')
        IMF = 'IMF', _('IMF: Imago Orpheus')
        IT = 'IT', _('IT: Impulse Tracker')
        J2B = 'J2B', _('J2B: Galaxy Sound System')
        MED = 'MED', _('MED: Octamed')
        MDL = 'MDL', _('MDL: Digitrakker')
        MO3 = 'MO3', _('MO3: Compressed Module')
        MOD = 'MOD', _('MOD: Protracker, Generic MOD')
        MPTM = 'MPTM', _('MPTM: OpenMPT')
        MT2 = 'MT2', _('MT2: MadTracker 2')
        MTM = 'MTM', _('MTM: Multi Tracker')
        OKT = 'OKT', _('OKT: Oktalyzer')
        PLM = 'PLM', _('PLM: Disorder Tracker 2')
        PSM = 'PSM', _('PSM: Epic MegaGames MASI')
        PTM = 'PTM', _('PTM: PolyTracker')
        S3M = 'S3M', _('S3M: Scream Tracker 3')
        SFX = 'SFX', _('SFX: SoundFX / MultiMedia Sound')
        STM = 'STM', _('STM: Scream Tracker')
        STP = 'STP', _('STP: SoundTracker Pro II')
        STX = 'STX', _('STX: Scream Tracker Music Interface Kit')
        SymMOD = 'SymMOD', _('SymMOD: Symphonie / Symphonie Pro')
        ULT = 'ULT', _('ULT: UltraTracker')
        UMX = 'UMX', _('UMX: Unreal Music')
        XM = 'XM', _('XM: FastTracker 2')

    class Licenses(models.TextChoices):
        PUBLIC_DOMAIN = 'publicdomain', _('Public Domain')
        NON_COMMERCIAL = 'by-nc', _('Non-commercial')
        NON_COMMERCIAL_NO_DERIVATIVES = 'by-nc-nd', _('Non-commercial No Derivatives')
        NON_COMMERCIAL_SHARE_ALIKE = 'by-nc-sa', _('Non-commercial Share Alike')
        NO_DERIVATIVES = 'by-nd', _('No Derivatives')
        SHARE_ALIKE = 'by-sa', _('Share Alike')
        ATTRIBUTION = 'by', _('Attribution')
        CC0 = 'cc0', _('CC0')

    class Genres(models.TextChoices):
        ELECTRONIC_TECHNO = 'electronic-techno', _("Electronic - Techno")
        ELECTRONIC_DANCE = 'electronic-dance', _("Electronic - Dance")
        ELECTRONIC_AMBIENT = 'electronic-ambient', _("Electronic - Ambient")
        ELECTRONIC_TRANCE_GENERAL = 'trance-general', _("Trance - General")
        ELECTRONIC_OTHER = 'electronic-other', _("Electronic - Other")
        ELECTRONIC_GENERAL = 'electronic-general', _("Electronic - General")
        ELECTRONIC_DRUM_AND_BASS = 'electronic-drum-and-bass', _("Electronic - Drum & Bass")
        ELECTRONIC_HOUSE = 'electronic-house', _("Electronic - House")
        ELECTRONIC_RAVE = 'electronic-rave', _("Electronic - Rave")
        ELECTRONIC_TRANCE_DREAM = 'trance-dream', _("Trance - Dream")
        ELECTRONIC_BREAKBEAT = 'electronic-breakbeat', _("Electronic - Breakbeat")
        ELECTRONIC_INDUSTRIAL = 'electronic-industrial', _("Electronic - Industrial")
        ELECTRONIC_HARDCORE = 'electronic-hardcore', _("Electronic - Hardcore")
        ELECTRONIC_CHILLOUT = 'chillout', _("Chillout")
        ELECTRONIC_TRANCE_GOA = 'trance-goa', _("Trance - Goa")
        ELECTRONIC_JUNGLE = 'electronic-jungle', _("Electronic - Jungle")
        ELECTRONIC_TRANCE_ACID = 'trance-acid', _("Trance - Acid")
        ELECTRONIC_IDM = 'electronic-idm', _("Electronic - IDM")
        ELECTRONIC_PROGRESSIVE = 'electronic-progressive', _("Electronic - Progressive")
        ELECTRONIC_GABBER = 'electronic-gabber', _("Electronic - Gabber")
        ELECTRONIC_MINIMAL = 'electronic-minimal', _("Electronic - Minimal")
        ELECTRONIC_TRANCE_HARD = 'trance-hard', _("Trance - Hard")
        ELECTRONIC_TRANCE_PROGRESSIVE = 'trance-progressive', _("Trance - Progressive")
        ELECTRONIC_TRANCE_TRIBAL = 'trance-tribal', _("Trance - Tribal")
        DEMO_CHIPTUNE = 'chiptune', _("Chiptune")
        DEMO_STYLE = 'demostyle', _("Demostyle")
        DEMO_1HRCOMPO = 'one-hour-compo', _("One-Hour Compo")
        POP_GENERAL = 'pop-general', _("Pop - General")
        POP_SYNTH = 'pop-synth', _("Pop - Synth")
        POP_SOFT = 'pop-soft', _("Pop - Soft")
        POP_ROCK_GENERAL = 'rock-general', _("Rock - General")
        POP_ROCK_SOFT = 'rock-soft', _("Rock - Soft")
        POP_ROCK_HARD = 'rock-hard', _("Rock - Hard")
        POP_FUNK = 'funk', _("Funk")
        POP_DISCO = 'disco', _("Disco")
        POP_BALLAD = 'ballad', _("Ballad")
        POP_EASY_LISTENING = 'easy-listening', _("Easy Listening")
        OTHER_VIDEO_GAME = 'video-game', _("Video Game")
        OTHER_ORCH = 'orchestral', _("Orchestral")
        OTHER_CLASSICAL = 'classical', _("Classical")
        OTHER_PIANO = 'piano', _("Piano")
        OTHER_FANTASY = 'fantasy', _("Fantasy")
        OTHER_SOUNDTRACK = 'soundtrack', _("Soundtrack")
        OTHER_COMEDY = 'comedy', _("Comedy")
        OTHER_MEDIEVAL = 'medieval', _("Medieval")
        OTHER_SPIRITUAL = 'spiritual', _("Spiritual")
        OTHER_RELIGIOUS = 'religious', _("Religious")
        OTHER_EXPERIMENTAL = 'experimental', _("Experimental")
        OTHER_NEWAGE = 'new-age', _("New Age")
        OTHER_FOLK = 'folk', _("Folk")
        OTHER_COUNTRY = 'country', _("Country")
        OTHER_BLUEGRASS = 'bluegrass', _("Bluegrass")
        OTHER_WORLD = 'world', _("World")
        OTHER_WORLD_LATIN = 'world-latin', _("World - Latin")
        OTHER_FUSION = 'fusion', _("Fusion")
        OTHER_VOX_MONTAGE = 'vocal-montage', _("Vocal Montage")
        OTHER_OTHER = 'other', _("Other")
        ALTERNATIVE = 'alternative', _("Alternative")
        ALTERNATIVE_GOTHIC = 'gothic', _("Gothic")
        ALTERNATIVE_PUNK = 'punk', _("Punk")
        ALTERNATIVE_METAL = 'metal-general', _("Metal - General")
        ALTERNATIVE_METAL_EXTREME = 'metal-extreme', _("Metal - Extreme")
        ALTERNATIVE_GRUNGE = 'grunge', _("Grunge")
        JAZZ = 'jazz-general', _("Jazz - General")
        JAZZ_MODERN = 'jazz-modern', _("Jazz - Modern")
        JAZZ_ACID = 'jazz-acid', _("Jazz - Acid")
        JAZZ_BLUES = 'blues', _("Blues")
        JAZZ_SWING = 'swing', _("Swing")
        JAZZ_BIG_BAND = 'big-band', _("Big Band")
        HIP_HOP = 'hip-hop', _("Hip-Hop")
        REGGAE = 'reggae', _("Reggae")
        R_AND_B = 'r-n-b', _("R&B")
        SOUL = 'soul', _("Soul")
        SKA = 'ska', _("Ska")
        CHRISTMAS = 'christmas', _("Christmas")
        HALLOWEEN = 'halloween', _("Halloween")

    legacy_id=models.IntegerField(null=True, db_index=True, blank=True)
    filename=models.CharField(max_length=120, db_index=True)
    filename_unzipped = models.CharField(max_length=120, blank=True)
    title=models.CharField(max_length=120, db_index=True)
    title_from_file = models.CharField(max_length=120, blank=True)
    format=models.CharField(max_length=6, choices=Formats.choices, db_index=True)
    file_size=models.PositiveIntegerField()
    channels=models.PositiveSmallIntegerField()
    instrument_text=models.TextField(max_length=64000, blank=True, null=True)
    comment_text=models.TextField(max_length=64000, blank=True, null=True)
    hash=models.CharField(max_length=33)
    pattern_hash=models.CharField(max_length=16, null=True, blank=True)
    license=models.CharField(max_length=16, choices=Licenses.choices, null=True, blank=True)
    search_document=SearchVectorField(null=True, blank=True)
    genre=models.CharField(choices=Genres.choices, null=True, blank=True, db_index=True, max_length=32)
    is_featured=models.BooleanField(null=True, blank=True, db_index=True)
    featured_date=models.DateTimeField(null=True, blank=True)
    featured_by=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='featured_by')
    folder=models.CharField(max_length=4)
    title_vector=SearchVectorField(null=True, blank=True)
    instrument_text_vector=SearchVectorField(null=True, blank=True)
    comment_text_vector=SearchVectorField(null=True, blank=True)
    uploaded_by=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, db_index=True, related_name='uploaded_by')
    create_date=models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

    def get_title(self) -> str:
        title = str(self.title).strip()
        return str(self.filename) if not title else title

    def is_own_song(self, profile_id):
        return self.artist_set.all().filter(profile_id=profile_id).exists()

    def has_commented(self, profile_id):
        return self.comment_set.all().filter(profile_id=profile_id).exists()

    def has_artist_commented(self, profile_id):
        return self.artistcomment_set.all().filter(profile_id=profile_id).exists()

    def can_user_leave_comment(self, profile_id):
        return not self.is_own_song(profile_id) and not self.has_commented(profile_id)

    def display_file_size(self):
        if self.file_size >= 1000000:
            return f'{"{:.2f}".format(self.file_size / 1000000)} MB'

        if self.file_size >= 10000:
            return f'{"{:.2f}".format(self.file_size / 1000)} KB'

        return f'{self.file_size} bytes'

    def get_stats(self):
        if hasattr(self, 'songstats'):

songs/views/add_favorite_view.py
from django.db.models import F
from django.shortcuts import redirect, get_object_or_404

from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin

from songs.models import Song, Favorite

class AddFavoriteView(LoginRequiredMixin, View):
    def is_own_song(self, profile, song_id):
        return hasattr(profile, 'artist') and profile.artist.songs.filter(id=song_id).count() > 0

    def is_already_favorite(self, profile, song_id):
        return Favorite.objects.filter(profile=profile, song_id=song_id).count() > 0

    def get(self, request, *args, **kwargs):
        if (not self.is_own_song(self.request.user.profile, kwargs['pk']) and not self.is_already_favorite(self.request.user.profile, kwargs['pk'])):
            Favorite(profile_id=self.request.user.profile.id, song_id=kwargs['pk']).save()
            song = get_object_or_404(Song, pk=kwargs['pk'])
            song_stats = song.get_stats()
            song_stats.total_favorites = F('total_favorites') + 1
            song_stats.save()
        return redirect('view_song', kwargs['pk'])

songs/views/comment_view.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from django.views.generic.base import ContextMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.shortcuts import redirect, render
from django.http import Http404

from songs.models import Song
from songs import forms

class CommentView(LoginRequiredMixin, ContextMixin, View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)

        try:
            song = Song.objects.get(pk=kwargs['pk'])
        except ObjectDoesNotExist as exc:
            raise Http404 from exc

        # Users cannot comment on their own song or songs they have already commented on
        if not song.can_user_leave_comment(request.user.profile.id):
            return redirect('view_song', kwargs['pk'])

        self.extra_context = {'song': song}

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        song = self.extra_context['song']
        context = {'song': song}

        # If the song does not have a genre, the user leaving the comment may assign it
        if not song.genre:
            song_form = forms.SongGenreForm(instance=song)
            context['song_form'] = song_form

        comment_form = forms.AddCommentForm()
        context['comment_form'] = comment_form

        return render(request, 'add_comment.html', context)

    def post(self, request, *args, **kwargs):
        song = self.extra_context['song']
        comment_form = forms.AddCommentForm(request.POST)

        # Only update the genre if the genre is not set in the song
        if not song.genre:
            song_form = forms.SongGenreForm(request.POST, instance=song)
        else:
            song_form = None

        # If song_form is None, that means we don't need to validate that form
        both_forms_valid = comment_form.is_valid() and (not song_form or song_form.is_valid())

        if both_forms_valid:
            with transaction.atomic():
                comment_instance = comment_form.save(commit=False)
                comment_instance.profile = self.request.user.profile
                comment_instance.song_id = song.pk
                comment_form.save()
                # If song_form is not None, that means we have a genre to update on the song
                if song_form:
                    song_form.save()
            return redirect('view_song', kwargs['pk'])

        return render(request, 'add_comment.html', {'song': song, 'song_form': song_form, 'comment_form': comment_form})

songs/views/player_view.py
from django.views.generic import TemplateView
from songs.models import Song

class PlayerView(TemplateView):
    template_name='tma_player.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     song_id = self.request.GET.get("song_id")
    #     song = Song.objects.get(pk = song_id)
    #     context['song'] = song
    #     return context

songs/templates/partials/page_navigation.html
{% load filters %}

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item {% if page_obj.number == 1 %}disabled{% endif %}">
            {% if page_obj.number != 1 %}
                <a class="page-link" href="?{{ request.GET|url_with_page:1 }}" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            {% else %}
                <span class="page-link" aria-hidden="true">&laquo;&laquo;</span>
            {% endif %}
        </li>
        <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?{{ request.GET|url_with_page:page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            {% else %}
                <span class="page-link" aria-hidden="true">&laquo;</span>
            {% endif %}
        </li>
        <li class="page-item">
            <div class="input-group">
                <select class="form-select" id="pageDropdown" onchange="location = this.value;">
                    {% for i in full_page_range %}
                        <option value="?{{ request.GET|url_with_page:i }}" {% if page_obj.number == i %}selected{% endif %}>{{ i }}</option>
                    {% endfor %}
                </select>
            </div>
        </li>
        <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
            {% if page_obj.has_next %}
                <a class="page-link" href="?{{ request.GET|url_with_page:page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% else %}
                <span class="page-link" aria-hidden="true">&raquo;</span>
            {% endif %}
        </li>
        <li class="page-item {% if page_obj.number == page_obj.paginator.num_pages %}disabled{% endif %}">
            {% if page_obj.number != page_obj.paginator.num_pages %}
                <a class="page-link" href="?{{ request.GET|url_with_page:page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            {% else %}
                <span class="page-link" aria-hidden="true">&raquo;&raquo;</span>
            {% endif %}
        </li>
    </ul>
</nav>

songs/templates/partials/song_artist_comments.html
{% load markdownify %}
{% load filters %}

{% if song.artistcomment_set.all %}
    <div>
        <div class="fs-5">Artist Comments</div>
        {% for comment in song.artistcomment_set.all %}
            <div class="bg-success bg-opacity-25 border border-dark rounded p-1">
                <div class="fw-bold">
                    Posted by <a href="{% url 'view_profile' comment.profile.id %}">{{comment.profile.display_name}}</a> on {{comment.create_date|date:"F j, o"}}
                    <br>
                </div>
                <br>
                {{comment.text|markdownify:"artist_comment"|modpage|safe }}
                {% if user.is_authenticated and is_own_song and comment.profile_id == user.profile.id %}
                    <span class="fs-6"><a href="{% url 'song_details' song.id %}">Update your comment</a></span>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endif %}

songs/templates/partials/song_comments.html
{% load markdownify %}
{% load filters %}

{% if song.comment_set.all %}
    <div class="mt-1">
        <div class="fs-5">Comments</div>
        {% for comment in song.comment_set.all %}
            <div class="bg-success bg-opacity-25 border border-dark rounded p-1 my-2">
                <div class="fw-bold">
                    {% if comment.profile %}
                        Posted by <a href="{% url 'view_profile' comment.profile.id %}">{{comment.profile.display_name}}</a> on {{comment.create_date|date:"F j, o"}}
                    {% else %}
                        Posted by Anonymous Modarchive User on {{comment.create_date|date:"F j, o"}}
                    {% endif %}
                    <br>
                    Rating: {{comment.rating}}/10
                </div>
                <br>
                {{comment.text|markdownify:"comment"|modpage|safe}}
            </div>
        {% endfor %}
    </div>
{% endif %}

songs/templates/partials/song_favorites.html
<div class="my-1">
    <div class="fs-5">People who like this tune</div>
    <div class="bg-success bg-opacity-25 border border-dark rounded p-1">
        {% for favorite in song.favorite_set.all %}
            <a href="{% url 'view_profile' favorite.profile_id %}">{{ favorite.profile.display_name }}</a>
        {% empty %}
            None yet
        {% endfor %}
    </div>
</div>

songs/templates/partials/song_info_and_stats.html
{% load bootstrap_icons %}
<div class="d-flex flex-wrap">
    <div class="badge text-bg-secondary me-1 mb-1">{% bs_icon 'code-square' size='1.0em' %}{{song.get_format_display}}</div>
    <div class="badge text-bg-secondary me-1 mb-1">{% bs_icon 'box2' size='1.0em' %}{{song.display_file_size}}</div>
    <div class="badge text-bg-secondary me-1 mb-1">{% bs_icon 'layout-three-columns' size='1.0em' %}{{song.channels}} channels</div>
    {% if song.genre %}
        <div class="badge text-bg-primary bg-opacity-75 me-1 mb-1">{% bs_icon 'music-note-beamed' size='1.0em' %} {{ song.get_genre_display }}</div>
    {% endif %}
    <div class="badge text-bg-success bg-opacity-75 me-1 mb-1">{% bs_icon 'download' size='1.0em' %}{{ stats.downloads }} downloads</div>
    <div class="badge text-bg-success bg-opacity-75 me-1 mb-1">{% bs_icon 'heart-fill' size='1.0em' %}{{ stats.total_favorites }} favorites</div>
    <div class="badge text-bg-success bg-opacity-75 me-1 mb-1">{% bs_icon 'chat-left-text' size='1.0em' %}{{ stats.total_comments }} comments</div>
    {% if stats.average_comment_score > 0.0 %}
        <div class="badge text-bg-success bg-opacity-75 mb-1">{% bs_icon 'star' size='1.0em' %}{{ stats.average_comment_score }} average rating</div>
    {% endif %}
</div>
{% if song.is_featured %}
    <div class="fst-italic text-secondary">
        This song was spotlit on {{ song.featured_date|date:"M d, Y" }}
    </div>
{% endif %}

songs/templates/partials/song_internal_text.html
{% load filters %}

{% if song.title_from_file and song.title_from_file != song.title %}
    <div class="fs-5 my-1">
        Original Title
    </div>

    <div class="text-warning bg-dark rounded px-3 py-1 font-monospace internal-comment">
        {{ song.title_from_file|spaces|escape }}
    </div>
{% endif  %}

{% if song.comment_text %}
    <div class="fs-5 my-1">
        Internal Comments
    </div>
    
    <div class="text-warning bg-dark rounded p-3 font-monospace internal-comment">
        {{ song.comment_text|hide_email_address|linebreaks|spaces|escape }}
    </div>
{% endif %}

{% if song.instrument_text %}
    <div class="fs-5 my-1">
        Instrument Text
    </div>    

    <div class="text-warning bg-dark rounded p-3 font-monospace internal-comment">
        {{ song.instrument_text|hide_email_address|linebreaks|spaces|escape }}
    </div>
{% endif %}

songs/templates/partials/song_title_and_links.html
{% load bootstrap_icons %}

<div class="">
    <div class="row justify-content-between">
        <div class="col-sm-6">
            <span class="fs-4">
                {% if song.is_featured %} {% bs_icon 'star-fill' %}{% endif %} 
                {{ song.get_title }}
            </span>
            <span class="text-secondary fs-6">({{song.filename}})</span>
            {% if perms.interactions.add_artistcomment and is_own_song %}
                <a href="{% url 'song_details' song.id %}">{% bs_icon 'pencil' %} Edit details</a>
            {% endif %}
        </div>
        {% if song.artist_set.all %}
        <div class="col-sm-4 text-sm-end fs-5">
            {% include 'song_artists.html' with song=song %}
        </div>
        {% endif %}
    </div>
    <div class="text-secondary mx-2 fst-italic">
        added on {{ song.create_date|date:"M d, Y" }}
    </div>

    <div class="row justify-content-between">
        <div class="col-sm my-1">
            <a class="btn btn-success" href="{% url 'song_download' song.id %}">{% bs_icon 'download' %} Download</button></a>
            <a class="btn btn-success" href="#" onclick="window.open('{% url 'player' %}?song_id={{song.id}}', 'keep');">{% bs_icon 'headphones' %} Listen</button></a>
        </div>

        {% if user.is_authenticated %}
        <div class="col-sm-5 btn-group mb-1" role="group">
            {% if perms.interactions.add_comment and can_comment %}
                <a class="btn btn-outline-primary" href="{% url 'add_comment' song.id %}">{% bs_icon 'chat-left-text' %} Add comment</a>
            {% endif %}

            {% if not is_own_song %}
                {% if perms.interactions.delete_favorite and is_favorite %}
                    <a class="btn btn-outline-primary" href="{% url 'remove_favorite' song.id %}">{% bs_icon 'heart-fill' %} Remove song from favorites</a>
                {% elif perms.interactions.add_favorite %}
                    <a class="btn btn-outline-primary" href="{% url 'add_favorite' song.id %}">{% bs_icon 'heart' %} Add song to favorites</a>
                {% endif %}
            {% endif %}
        </div>
        {% endif %}
    </div>
    
    <hr>
</div>