api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SongViewSet, ArtistViewSet, SongSearchAPIView, SongDownloadView

router = DefaultRouter()
router.register(r'songs', SongViewSet)
router.register(r'artists', ArtistViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('search', SongSearchAPIView.as_view()),
    path('download/<int:pk>', SongDownloadView.as_view(), name='song_download'),
]

modarchive/urls.py
from django.contrib import admin
from django.urls.conf import include, re_path
from django.urls import path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('homepage.urls')),
    path('songs/', include('songs.urls')),
    path('api/v1/', include('api.urls')),
    path('artists/', include('artists.urls')),
    path('search/', include('search.urls')),
    path('uploads/', include('uploads.urls')),
    path('interactions/', include('interactions.urls')),
    # path('account/sceneid/', include('sceneid.urls')),
]

artists/models.py
import random
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone

from homepage.models import Profile
from songs.models import Song

User = get_user_model()

class Artist(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        primary_key=False,
        null=True,
        blank=True
    )
    profile = models.OneToOneField(
        Profile,
        on_delete=models.SET_NULL,
        primary_key=False,
        null=True,
        blank=True
    )
    legacy_id=models.IntegerField(null=True, blank=True, help_text="User ID from the legacy Mod Archive site", db_index=True)
    key=models.CharField(max_length=32, db_index=True, blank=True)
    name=models.CharField(max_length=64)
    random_token=models.PositiveIntegerField(null=True, blank=True, help_text="Used for differentiating artists with the same name")
    songs=models.ManyToManyField(Song, through='ArtistSong', blank=True)
    search_document=SearchVectorField(null=True)
    create_date=models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            GinIndex(fields=['search_document'])
        ]
        unique_together = [
            ['name', 'random_token']
        ]

    def index_components(self):
        return {
            'A': self.name
        }

    def __str__(self):
        return str(self.name)

class ArtistSong(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('artist', 'song')

@receiver(pre_save, sender=Artist)
def set_random_number(sender, instance, **kwargs):
    # Generate a random 4-digit number only if it's a new artist or if there is a conflict
    if instance._state.adding or Artist.objects.filter(name=instance.name, random_token=instance.random_token).exclude(pk=instance.pk).exists():
        instance.random_token = random.randint(1000, 9999)

modarchive/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}The Mod Archive{% endblock title %}</title>
        {% block css %}
            {% font_awesome %}
            <link rel="stylesheet" href="{% static 'bulma/css/style.min.css' %}">
            {% block extra_css %}{% endblock extra_css %}
        {% endblock css %}

        {% block script %}
        {% endblock script %}
    </head>
    <body>
        {% include 'navbar.html' %}

        {% comment %} Main page content {% endcomment %}
        <section class='section'>
            <div class='columns'>
                <div class='column is-8 is-offset-2 has-background-white'>
                    <div class='container'>
                        {% block content %}
                
                        {% endblock %}
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

modarchive/templates/form_field.html
<div class='field'>
    {{ element }}
    {% if errors %}
        <div class='text-danger is-size-7 is-italic'>
            {{ errors }}
        </div>
    {% endif %}
</div>

modarchive/templates/song_artists.html
{% if song.artist_set.all %}
    by {% for artist in song.artist_set.all %}
        {% if not forloop.first %}{% if forloop.last %} and {% else %}, {% endif %}{% endif %}
        <a href="{% url 'view_artist' artist.id %}">{{ artist.name }}</a>
    {% endfor %}
{% endif %}