api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SongViewSet, ArtistViewSet, SongSearchAPIView, SongDownloadView

router = DefaultRouter()
router.register(r'songs', SongViewSet)
router.register(r'artists', ArtistViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('search', SongSearchAPIView.as_view()),
    path('download/<int:pk>', SongDownloadView.as_view(), name='song_download'),
]

artists/urls.py
from django.urls import path

from artists.views import artist_view

urlpatterns = [
    path('', artist_view.ArtistListView.as_view(), {}, 'artists'),
    path('<int:pk>/', artist_view.ArtistDetailView.as_view(), {}, 'view_artist'),
    path('<int:pk>/songs', artist_view.ArtistSongsView.as_view(), {}, 'view_artist_songs'),
    path('<int:pk>/comments', artist_view.ArtistCommentsView.as_view(), {}, 'view_artist_comments'),
    path('<int:pk>/favorites', artist_view.ArtistFavoritesView.as_view(), {}, 'view_artist_favorites'),
]

artists/models.py
import random
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone

from homepage.models import Profile
from songs.models import Song

User = get_user_model()

class Artist(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        primary_key=False,
        null=True,
        blank=True
    )
    profile = models.OneToOneField(
        Profile,
        on_delete=models.SET_NULL,
        primary_key=False,
        null=True,
        blank=True
    )
    legacy_id=models.IntegerField(null=True, blank=True, help_text="User ID from the legacy Mod Archive site", db_index=True)
    key=models.CharField(max_length=32, db_index=True, blank=True)
    name=models.CharField(max_length=64)
    random_token=models.PositiveIntegerField(null=True, blank=True, help_text="Used for differentiating artists with the same name")
    songs=models.ManyToManyField(Song, through='ArtistSong', blank=True)
    search_document=SearchVectorField(null=True)
    create_date=models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            GinIndex(fields=['search_document'])
        ]
        unique_together = [
            ['name', 'random_token']
        ]

    def index_components(self):
        return {
            'A': self.name
        }

    def __str__(self):
        return str(self.name)

class ArtistSong(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('artist', 'song')

@receiver(pre_save, sender=Artist)
def set_random_number(sender, instance, **kwargs):
    # Generate a random 4-digit number only if it's a new artist or if there is a conflict
    if instance._state.adding or Artist.objects.filter(name=instance.name, random_token=instance.random_token).exclude(pk=instance.pk).exists():
        instance.random_token = random.randint(1000, 9999)

songs/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.postgres.search import SearchVectorField
from django.contrib.postgres.indexes import GinIndex
from django.core.exceptions import ValidationError
from django.conf import settings

from homepage.models import Profile

class Song(models.Model):
    class Formats(models.TextChoices):
        _669 = '669', _('669: Composer 669 / UNIS 669')
        AHX = 'AHX', _('AHX: Abyss\' Highest eXperience, formerly THX')
        AMF = 'AMF', _('AMF: ASYLUM / DSMI')
        AMS = 'AMS', _('AMS: Extreme\'s Tracker / Velvet Studio')
        C67 = 'C67', _('C67: CDFM / Composer 670')
        DBM = 'DBM', _('DBM: Digi Booster Pro')
        DIGI = 'DIGI', _('DIGI: Digi Booster')
        DMF = 'DMF', _('DMF: X-Tracker')
        DSM = 'DSM', _('DSM: DSIK')
        DSYM = 'DSYM', _('DSYM: Digital Symphony')
        DTM = 'DTM', _('DTM: Digital Tracker / Digital Home Studio')
        FAR = 'FAR', _('FAR: Farandole Composer')
        FMT = 'FMT', _('FMT: FM Tracker')
        GDM = 'GDM', _('GDM: BWSB Sound System')
        HVL = 'HVL', _('HVL: HivelyTracker')
        IMF = 'IMF', _('IMF: Imago Orpheus')
        IT = 'IT', _('IT: Impulse Tracker')
        J2B = 'J2B', _('J2B: Galaxy Sound System')
        MED = 'MED', _('MED: Octamed')
        MDL = 'MDL', _('MDL: Digitrakker')
        MO3 = 'MO3', _('MO3: Compressed Module')
        MOD = 'MOD', _('MOD: Protracker, Generic MOD')
        MPTM = 'MPTM', _('MPTM: OpenMPT')
        MT2 = 'MT2', _('MT2: MadTracker 2')
        MTM = 'MTM', _('MTM: Multi Tracker')
        OKT = 'OKT', _('OKT: Oktalyzer')
        PLM = 'PLM', _('PLM: Disorder Tracker 2')
        PSM = 'PSM', _('PSM: Epic MegaGames MASI')
        PTM = 'PTM', _('PTM: PolyTracker')
        S3M = 'S3M', _('S3M: Scream Tracker 3')
        SFX = 'SFX', _('SFX: SoundFX / MultiMedia Sound')
        STM = 'STM', _('STM: Scream Tracker')
        STP = 'STP', _('STP: SoundTracker Pro II')
        STX = 'STX', _('STX: Scream Tracker Music Interface Kit')
        SymMOD = 'SymMOD', _('SymMOD: Symphonie / Symphonie Pro')
        ULT = 'ULT', _('ULT: UltraTracker')
        UMX = 'UMX', _('UMX: Unreal Music')
        XM = 'XM', _('XM: FastTracker 2')

    class Licenses(models.TextChoices):
        PUBLIC_DOMAIN = 'publicdomain', _('Public Domain')
        NON_COMMERCIAL = 'by-nc', _('Non-commercial')
        NON_COMMERCIAL_NO_DERIVATIVES = 'by-nc-nd', _('Non-commercial No Derivatives')
        NON_COMMERCIAL_SHARE_ALIKE = 'by-nc-sa', _('Non-commercial Share Alike')
        NO_DERIVATIVES = 'by-nd', _('No Derivatives')
        SHARE_ALIKE = 'by-sa', _('Share Alike')
        ATTRIBUTION = 'by', _('Attribution')
        CC0 = 'cc0', _('CC0')

    class Genres(models.TextChoices):
        ELECTRONIC_TECHNO = 'electronic-techno', _("Electronic - Techno")
        ELECTRONIC_DANCE = 'electronic-dance', _("Electronic - Dance")
        ELECTRONIC_AMBIENT = 'electronic-ambient', _("Electronic - Ambient")
        ELECTRONIC_TRANCE_GENERAL = 'trance-general', _("Trance - General")
        ELECTRONIC_OTHER = 'electronic-other', _("Electronic - Other")
        ELECTRONIC_GENERAL = 'electronic-general', _("Electronic - General")
        ELECTRONIC_DRUM_AND_BASS = 'electronic-drum-and-bass', _("Electronic - Drum & Bass")
        ELECTRONIC_HOUSE = 'electronic-house', _("Electronic - House")
        ELECTRONIC_RAVE = 'electronic-rave', _("Electronic - Rave")
        ELECTRONIC_TRANCE_DREAM = 'trance-dream', _("Trance - Dream")
        ELECTRONIC_BREAKBEAT = 'electronic-breakbeat', _("Electronic - Breakbeat")
        ELECTRONIC_INDUSTRIAL = 'electronic-industrial', _("Electronic - Industrial")
        ELECTRONIC_HARDCORE = 'electronic-hardcore', _("Electronic - Hardcore")
        ELECTRONIC_CHILLOUT = 'chillout', _("Chillout")
        ELECTRONIC_TRANCE_GOA = 'trance-goa', _("Trance - Goa")
        ELECTRONIC_JUNGLE = 'electronic-jungle', _("Electronic - Jungle")
        ELECTRONIC_TRANCE_ACID = 'trance-acid', _("Trance - Acid")
        ELECTRONIC_IDM = 'electronic-idm', _("Electronic - IDM")
        ELECTRONIC_PROGRESSIVE = 'electronic-progressive', _("Electronic - Progressive")
        ELECTRONIC_GABBER = 'electronic-gabber', _("Electronic - Gabber")
        ELECTRONIC_MINIMAL = 'electronic-minimal', _("Electronic - Minimal")
        ELECTRONIC_TRANCE_HARD = 'trance-hard', _("Trance - Hard")
        ELECTRONIC_TRANCE_PROGRESSIVE = 'trance-progressive', _("Trance - Progressive")
        ELECTRONIC_TRANCE_TRIBAL = 'trance-tribal', _("Trance - Tribal")
        DEMO_CHIPTUNE = 'chiptune', _("Chiptune")
        DEMO_STYLE = 'demostyle', _("Demostyle")
        DEMO_1HRCOMPO = 'one-hour-compo', _("One-Hour Compo")
        POP_GENERAL = 'pop-general', _("Pop - General")
        POP_SYNTH = 'pop-synth', _("Pop - Synth")
        POP_SOFT = 'pop-soft', _("Pop - Soft")
        POP_ROCK_GENERAL = 'rock-general', _("Rock - General")
        POP_ROCK_SOFT = 'rock-soft', _("Rock - Soft")
        POP_ROCK_HARD = 'rock-hard', _("Rock - Hard")
        POP_FUNK = 'funk', _("Funk")
        POP_DISCO = 'disco', _("Disco")
        POP_BALLAD = 'ballad', _("Ballad")
        POP_EASY_LISTENING = 'easy-listening', _("Easy Listening")
        OTHER_VIDEO_GAME = 'video-game', _("Video Game")
        OTHER_ORCH = 'orchestral', _("Orchestral")
        OTHER_CLASSICAL = 'classical', _("Classical")
        OTHER_PIANO = 'piano', _("Piano")
        OTHER_FANTASY = 'fantasy', _("Fantasy")
        OTHER_SOUNDTRACK = 'soundtrack', _("Soundtrack")
        OTHER_COMEDY = 'comedy', _("Comedy")
        OTHER_MEDIEVAL = 'medieval', _("Medieval")
        OTHER_SPIRITUAL = 'spiritual', _("Spiritual")
        OTHER_RELIGIOUS = 'religious', _("Religious")
        OTHER_EXPERIMENTAL = 'experimental', _("Experimental")
        OTHER_NEWAGE = 'new-age', _("New Age")
        OTHER_FOLK = 'folk', _("Folk")
        OTHER_COUNTRY = 'country', _("Country")
        OTHER_BLUEGRASS = 'bluegrass', _("Bluegrass")
        OTHER_WORLD = 'world', _("World")
        OTHER_WORLD_LATIN = 'world-latin', _("World - Latin")
        OTHER_FUSION = 'fusion', _("Fusion")
        OTHER_VOX_MONTAGE = 'vocal-montage', _("Vocal Montage")
        OTHER_OTHER = 'other', _("Other")
        ALTERNATIVE = 'alternative', _("Alternative")
        ALTERNATIVE_GOTHIC = 'gothic', _("Gothic")
        ALTERNATIVE_PUNK = 'punk', _("Punk")
        ALTERNATIVE_METAL = 'metal-general', _("Metal - General")
        ALTERNATIVE_METAL_EXTREME = 'metal-extreme', _("Metal - Extreme")
        ALTERNATIVE_GRUNGE = 'grunge', _("Grunge")
        JAZZ = 'jazz-general', _("Jazz - General")
        JAZZ_MODERN = 'jazz-modern', _("Jazz - Modern")
        JAZZ_ACID = 'jazz-acid', _("Jazz - Acid")
        JAZZ_BLUES = 'blues', _("Blues")
        JAZZ_SWING = 'swing', _("Swing")
        JAZZ_BIG_BAND = 'big-band', _("Big Band")
        HIP_HOP = 'hip-hop', _("Hip-Hop")
        REGGAE = 'reggae', _("Reggae")
        R_AND_B = 'r-n-b', _("R&B")
        SOUL = 'soul', _("Soul")
        SKA = 'ska', _("Ska")
        CHRISTMAS = 'christmas', _("Christmas")
        HALLOWEEN = 'halloween', _("Halloween")

    legacy_id=models.IntegerField(null=True, db_index=True, blank=True)
    filename=models.CharField(max_length=120, db_index=True)
    filename_unzipped = models.CharField(max_length=120, blank=True)
    title=models.CharField(max_length=120, db_index=True)
    title_from_file = models.CharField(max_length=120, blank=True)
    format=models.CharField(max_length=6, choices=Formats.choices, db_index=True)
    file_size=models.PositiveIntegerField()
    channels=models.PositiveSmallIntegerField()
    instrument_text=models.TextField(max_length=64000, blank=True, null=True)
    comment_text=models.TextField(max_length=64000, blank=True, null=True)
    hash=models.CharField(max_length=33)
    pattern_hash=models.CharField(max_length=16, null=True, blank=True)
    license=models.CharField(max_length=16, choices=Licenses.choices, null=True, blank=True)
    search_document=SearchVectorField(null=True, blank=True)
    genre=models.CharField(choices=Genres.choices, null=True, blank=True, db_index=True, max_length=32)
    is_featured=models.BooleanField(null=True, blank=True, db_index=True)
    featured_date=models.DateTimeField(null=True, blank=True)
    featured_by=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name='featured_by')
    folder=models.CharField(max_length=4)
    title_vector=SearchVectorField(null=True, blank=True)
    instrument_text_vector=SearchVectorField(null=True, blank=True)
    comment_text_vector=SearchVectorField(null=True, blank=True)
    uploaded_by=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, db_index=True, related_name='uploaded_by')
    create_date=models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

    def get_title(self) -> str:
        title = str(self.title).strip()
        return str(self.filename) if not title else title

    def is_own_song(self, profile_id):
        return self.artist_set.all().filter(profile_id=profile_id).exists()

    def has_commented(self, profile_id):
        return self.comment_set.all().filter(profile_id=profile_id).exists()

    def has_artist_commented(self, profile_id):
        return self.artistcomment_set.all().filter(profile_id=profile_id).exists()

    def can_user_leave_comment(self, profile_id):
        return not self.is_own_song(profile_id) and not self.has_commented(profile_id)

    def display_file_size(self):
        if self.file_size >= 1000000:
            return f'{"{:.2f}".format(self.file_size / 1000000)} MB'

        if self.file_size >= 10000:
            return f'{"{:.2f}".format(self.file_size / 1000)} KB'

        return f'{self.file_size} bytes'

    def get_stats(self):
        if hasattr(self, 'songstats'):

artists/views.py
from django.shortcuts import render

from artists.models import Artist

def artist(request, pk):
    if request.method == 'GET':
        artist = Artist.objects.get(pk = pk)
        return render(request, 'artist.html', context={'artist': artist})

artists/views/artist_view.py
from django.core.paginator import Paginator
from django.views.generic import DetailView, ListView

from artists.models import Artist
from songs.models import Song
from homepage.view.common_views import PageNavigationListView

class ArtistView(DetailView):
    model = Artist
    template_name = 'artist.html'

class ArtistDetailView(DetailView):
    model = Artist
    template_name = "artist_overview.html"

class ArtistSongsView(PageNavigationListView):
    model = Song
    template_name = "artist_songs.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['artist'] = self.artist
        return context_data

    def get_queryset(self):
        self.artist = Artist.objects.get(pk=self.kwargs['pk'])
        return self.artist.songs.all()

class ArtistFavoritesView(PageNavigationListView):
    model = Song
    template_name = "artist_favorites.html"
    items_per_page = 25
    context_object_name = 'favorites'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['artist'] = self.artist
        return context_data

    def get_queryset(self):
        self.artist = Artist.objects.get(pk=self.kwargs['pk'])
        return self.artist.profile.favorite_set.all()

class ArtistCommentsView(PageNavigationListView):
    model = Song
    template_name = "artist_comments.html"
    items_per_page = 15
    context_object_name = 'comments'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['artist'] = self.artist
        return context_data

    def get_queryset(self):
        self.artist = Artist.objects.get(pk=self.kwargs['pk'])
        return self.artist.profile.comment_set.all()

class ArtistListView(ListView):
    model = Artist
    template_name='artist_list.html'
    queryset=Artist.objects.order_by('-id')[:50]

artists/templates/artist.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{ artist.name }} artist profile
{% endblock %}

{% block content %}

{% if user.is_staff and perms.artists.change_artist %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_change' artist.id %}">Change this artist</a>
    </div>
{% endif %}

<div class='fs-2 title'>{{ artist.name }}</div>

{% if artist.profile %}
<p>
    Member since {{ artist.profile.create_date|date:"M d, Y" }}

    {% if user.profile and user.profile.id == artist.profile.id %}
        - <a href="{% url 'update_profile' %}">Update your profile</a>
    {% endif %}
</p>
{% endif %}


{% if artist.profile %}
    {% include 'partials/artist_with_profile.html' %}
{% else %}
    {% include 'partials/artist_without_profile.html' %}
{% endif %}

<p>
    <br/>
    <a href="{% url 'artists' %}">Back to artists index</a>
</p>

{% endblock %}

artists/templates/artist_comments.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{ artist.name }} comments
{% endblock %}

{% block content %}

{% if user.is_staff and perms.artists.change_artist %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_change' artist.id %}">Change this artist</a>
    </div>
{% endif %}

<div class='fs-2 title'>Comments by {{ artist.name }}</div>

{% if artist.profile %}
<p>
    Member since {{ artist.profile.create_date|date:"M d, Y" }}

    {% if user.profile and user.profile.id == artist.profile.id %}
        - <a href="{% url 'update_profile' %}">Update your profile</a>
    {% endif %}
</p>
{% endif %}

<ul class="nav nav-pills">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist' artist.pk %}">Overview</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_songs' artist.pk %}">Songs</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'view_artist_comments' artist.pk %}">Comments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_favorites' artist.pk %}">Favorites</a>
    </li>
</ul>

<hr>

<div class="tab-content">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for i in page_range|default_if_none:page_obj.paginator.get_elided_page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    {% if i == page_obj.paginator.ELLIPSIS %}
                        <li class="page-item"><span class="page-link">{{ i }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

    {% for comment in comments %}
        <div class="bg-success bg-opacity-25 border border-dark rounded p-1 mx-4 my-2">
            <div><strong>Song:</strong> <a href="{% url 'view_song' comment.song.id %}">{{comment.song.get_title}}</a> ({{comment.song.filename}}) {% include 'song_artists.html' with song=comment.song %}</div>
            <div><strong>Posted on:</strong> {{comment.create_date|date:"F j, o"}}</div>
            <div><strong>Rating:</strong> {{comment.rating}}/10</div>                        
            <br>
            {{comment.text|markdownify:"comment"}}
        </div>
    {% empty %}
        No comments
    {% endfor %}
</div>

<p>
    <br/>
    <a href="{% url 'artists' %}">Back to artists index</a>
</p>

{% endblock %}

artists/templates/artist_favorites.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{ artist.name }} favorites
{% endblock %}

{% block content %}

{% if user.is_staff and perms.artists.change_artist %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_change' artist.id %}">Change this artist</a>
    </div>
{% endif %}

<div class='fs-2 title'>Favorite songs of {{ artist.name }}</div>

{% if artist.profile %}
<p>
    Member since {{ artist.profile.create_date|date:"M d, Y" }}

    {% if user.profile and user.profile.id == artist.profile.id %}
        - <a href="{% url 'update_profile' %}">Update your profile</a>
    {% endif %}
</p>
{% endif %}

<ul class="nav nav-pills">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist' artist.pk %}">Overview</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_songs' artist.pk %}">Songs</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_comments' artist.pk %}">Comments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'view_artist_favorites' artist.pk %}">Favorites</a>
    </li>
</ul>

<hr>

<div class="tab-content">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for i in page_range|default_if_none:page_obj.paginator.get_elided_page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    {% if i == page_obj.paginator.ELLIPSIS %}
                        <li class="page-item"><span class="page-link">{{ i }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

    {% for favorite in favorites %}
        <li><a href="{% url 'view_song' favorite.song_id %}">{{ favorite.song.get_title }}</a></li>
    {% empty %}
        No favorites added
    {% endfor %}       
</div>

<p>
    <br/>
    <a href="{% url 'artists' %}">Back to artists index</a>
</p>

{% endblock %}

artists/templates/artist_list.html
{% extends 'base_page/base.html' %}

{% block title %}
    {{ block.super }}: Artists list
{% endblock %}

{% block content %}

<h2>Artists</h2>

{% if user.is_staff and perms.songs.change_song %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_add' %}">Add an artist</a>
    </div>
{% endif %}

{% for artist in object_list %}
    <div>
        <a href="{% url 'view_artist' artist.id %}">{{ artist.name }}</a>
    </div>
{% empty %}
    <div>No artists yet.</div>
{% endfor %}

{% endblock %}

artists/templates/artist_overview.html
{% extends 'base_page/base.html' %}
{% load markdownify %}
{% load filters %}

{% block title %}
    {{ block.super }}: {{ artist.name }} artist profile
{% endblock %}

{% block content %}

{% if user.is_staff and perms.artists.change_artist %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_change' artist.id %}">Change this artist</a>
    </div>
{% endif %}

<div class='fs-2 title'>{{ artist.name }}</div>

{% if artist.profile %}
<p>
    Member since {{ artist.profile.create_date|date:"M d, Y" }}

    {% if user.profile and user.profile.id == artist.profile.id %}
        - <a href="{% url 'update_profile' %}">Update your profile</a>
    {% endif %}
</p>
{% endif %}

<ul class="nav nav-pills">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'view_artist' artist.pk %}">Overview</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_songs' artist.pk %}">Songs</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_comments' artist.pk %}">Comments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_favorites' artist.pk %}">Favorites</a>
    </li>
</ul>

<hr>

<div class="tab-content mx-3 mt-2" id="myTabContent">
    {% if artist.profile.blurb %}
        {{ artist.profile.blurb|markdownify:"profile"|modpage|safe }}
    {% endif %}
</div>

<p>
    <br/>
    <a href="{% url 'artists' %}">Back to artists index</a>
</p>

{% endblock %}

artists/templates/artist_songs.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{ artist.name }} songs
{% endblock %}

{% block content %}

{% if user.is_staff and perms.artists.change_artist %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:artists_artist_change' artist.id %}">Change this artist</a>
    </div>
{% endif %}

<div class='fs-2 title'>Songs by {{ artist.name }}</div>

{% if artist.profile %}
<p>
    Member since {{ artist.profile.create_date|date:"M d, Y" }}

    {% if user.profile and user.profile.id == artist.profile.id %}
        - <a href="{% url 'update_profile' %}">Update your profile</a>
    {% endif %}
</p>
{% endif %}

<ul class="nav nav-pills">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist' artist.pk %}">Overview</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'view_artist_songs' artist.pk %}">Songs</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_comments' artist.pk %}">Comments</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_artist_favorites' artist.pk %}">Favorites</a>
    </li>
</ul>

<hr>

<div class="tab-content">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for i in page_range|default_if_none:page_obj.paginator.get_elided_page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }}</span>
                    </li>
                {% else %}
                    {% if i == page_obj.paginator.ELLIPSIS %}
                        <li class="page-item"><span class="page-link">{{ i }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </nav>
    
    <ul>
        {% for song in songs %}
        <li>
            <a href="{% url 'view_song' song.id %}">{{ song.get_title }}</a>
        </li>
        {% empty %}<li>No songs yet.</li>{% endfor %}
    </ul>        
</div>

<p>
    <br/>
    <a href="{% url 'artists' %}">Back to artists index</a>
</p>

{% endblock %}