api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SongViewSet, ArtistViewSet, SongSearchAPIView, SongDownloadView

router = DefaultRouter()
router.register(r'songs', SongViewSet)
router.register(r'artists', ArtistViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('search', SongSearchAPIView.as_view()),
    path('download/<int:pk>', SongDownloadView.as_view(), name='song_download'),
]

homepage/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from homepage.view import password_views, registration_views
from homepage.view.bulk_upload_view import BulkUploadView
from homepage.view.homepage_views import account_settings, LoginView, HomePageView
from homepage.view.legacy_redirect_view import LegacyUrlRedirectionView
from homepage.view.profile_view import ProfileView, UpdateProfileView, ProfileFavoritesView, ProfileCommentsView

urlpatterns = [
    # Basic homepage
    path('', HomePageView.as_view(), {}, 'home'),
    path('account_settings/', account_settings, {}, 'account_settings'),

    # Basic auth functionality
    path('login/', LoginView.as_view(), name='login', kwargs={'next': '/'}),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('change_password/', password_views.PasswordChangeView.as_view(), name='change_password'),

    # Account registration
    path('register/', registration_views.register, {}, 'register'),
    path('register_done/', TemplateView.as_view(template_name='registration/register_done.html'), {}, 'register_done'),
    path('register_fail/', TemplateView.as_view(template_name='registration/register_fail.html'), {}, 'register_fail'),
    path('activate_account/<uidb64>/<token>', registration_views.activate, name='activate_account'),
    path('account_activation_complete/', registration_views.AccountActivationCompleteView.as_view(), {}, 'account_activation_complete'),
    path('activation_error/', TemplateView.as_view(template_name='registration/account_activation_error.html'), {}, 'activation_error'),

    # Password reset
    path('forgot_password/', password_views.PasswordResetView.as_view(), {}, 'forgot_password'),
    path('password_reset_done/', password_views.password_reset_done, {}, 'password_reset_done'),
    path('password_reset/<uidb64>/<token>/', password_views.PasswordResetConfirmView.as_view(), name='password_reset'),
    path('password_reset_complete/', password_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Legacy URL redirects
    re_path('(?P<php_file>[a-zA-Z]+).php/', LegacyUrlRedirectionView.as_view(), name='login_php'),

    # Bulk uploader tool
    path('bulk_upload/', BulkUploadView.as_view(), {}, 'bulk_upload'),

    # Profiles
    path('profiles/<int:pk>/', ProfileView.as_view(), {}, 'view_profile'),
    path('profiles/<int:pk>/comments', ProfileCommentsView.as_view(), {}, 'view_profile_comments'),
    path('profiles/<int:pk>/favorites', ProfileFavoritesView.as_view(), {}, 'view_profile_favorites'),
    path('profiles/update/', UpdateProfileView.as_view(), {}, 'update_profile')
]

handler404 = 'homepage.view.homepage_views.page_not_found_view'

homepage/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        primary_key=False,
        null=True
    )
    legacy_id=models.IntegerField(null=True, db_index=True)
    display_name = models.CharField(max_length=255)
    blurb = models.TextField(max_length=24000, null=True, blank=True)
    create_date=models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.display_name)

    def has_comments(self):
        return self.comment_set.all().count() > 0

class BlacklistedDomain(models.Model):
    domain=models.CharField(max_length=255, unique=True)
    hits=models.IntegerField(default=0)
    added_by=models.ForeignKey(User, on_delete=models.RESTRICT)
    create_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

class News(models.Model):
    class Meta:
        verbose_name_plural = "news items"

    headline=models.CharField(max_length=500)
    content=models.TextField(max_length=5000)
    profile=models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    create_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)

interactions/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from songs.models import Song
from homepage.models import Profile

class Comment(models.Model):
    class Ratings(models.IntegerChoices):
        _1 = 1, _("1: Very poor")
        _2 = 2, _("2: Poor")
        _3 = 3, _("3: Listenable")
        _4 = 4, _("4: Good attempt")
        _5 = 5, _("5: Average")
        _6 = 6, _("6: Above average")
        _7 = 7, _("7: Enjoyable")
        _8 = 8, _("8: Very good")
        _9 = 9, _("9: Excellent")
        _10 = 10, _("10: Awesome")

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    rating = models.PositiveSmallIntegerField(choices=Ratings.choices)
    create_date = models.DateTimeField(default=timezone.now)

class ArtistComment(models.Model):
    class Meta:
        unique_together = ('profile', 'song')
        verbose_name_plural = 'artist comments'
        db_table = 'songs_artist_comments'

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    text = models.TextField(max_length=5000)
    create_date = models.DateTimeField(default=timezone.now)
    update_date=models.DateTimeField(auto_now=True)

class Favorite(models.Model):
    class Meta:
        unique_together = ('profile', 'song')

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)

homepage/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms.widgets import EmailInput
# from sceneid.forms import UserCreationForm as BaseUserCreationForm

from homepage.models import Profile
from homepage.fields import BlacklistProtectedEmailField

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control', 'placeholder': 'Password'}))
    remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput())

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control', 'placeholder': 'Current Password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New Password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Repeat New Password'}))

class RegisterUserForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'Username'}))
    email = BlacklistProtectedEmailField(widget=EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Repeat Password'}))

    def save(self, commit=False):
        user = super().save(commit=commit)

        # Test to see if a user already exists with that email address. If so, raise an error
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise EmailAddressInUseError("Email address is already in use.")

        user.is_active = False
        user.email = self.cleaned_data['email']

        user.save()
        return user

class ForgotPasswordForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class': 'form-control', 'placeholder': 'Email Address'}))

class ResetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New password confirmation'}))

class EmailAddressInUseError(Exception):
    pass

class CsvUploadForm(forms.Form):
    csv_file = forms.FileField()

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("blurb",)

# class SceneIDUserCreationForm(BaseUserCreationForm):
#     username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder': 'Username'}))

homepage/templates/home_page.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: Serving the Demoscene since 1996
{% endblock %}

{% block content %}
    {% if user.is_staff and perms.homepage.add_news %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Admin Actions</h4>
        <a href="{% url 'admin:homepage_news_add' %}">Add a news item</a>
    </div>
    {% endif %}    

    {% for news in latest_news %}
        <div class="border border-dark rounded p-1 my-2 bg-secondary bg-gradient bg-opacity-25">
            <div class="fw-bold fs-4">
                {{ news.headline }}
            </div>

            <div>
                posted by {{ news.profile.display_name }} on {{ news.create_date|date:"F j, o" }}
            </div>

            <p>
                {{ news.content|markdownify|linebreaks }}
            </p>

            {% if user.is_staff and perms.homepage.change_news %}
                <div><a href="{% url 'admin:homepage_news_change' news.id %}">Edit</a></div>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}    

homepage/templates/profile.html
{% extends 'base_page/base.html' %}
{% load markdownify %}
{% load filters %}

{% block title %}
    {{ block.super }}: {{profile.display_name}} profile
{% endblock %}

{% block content %}
    {% if user.profile and user.profile.id == profile.id %}
        <a href="{% url 'update_profile' %}">Update your profile</a>
        <br/><br/>
    {% endif %}

    <div class="fs-2">
        Profile: {{ profile.display_name }}
    </div>

    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'view_profile' profile.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile_comments' profile.pk %}">Comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile_favorites' profile.pk %}">Favorites</a>
        </li>
    </ul>
    
    <hr>

    <div class="tab-content mx-3 mt-2">
        <!-- Overview tab -->
        {% if profile.blurb %}
            {{ profile.blurb|markdownify:"profile"|modpage|safe }}
        {% endif %}
    </div>
{% endblock %}

homepage/templates/profile_comments.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{profile.display_name}} profile
{% endblock %}

{% block content %}
    {% if user.profile and user.profile.id == profile.id %}
        <a href="{% url 'update_profile' %}">Update your profile</a>
        <br/><br/>
    {% endif %}

    <div class="fs-2">
        Profile: {{ profile.display_name }}
    </div>

    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile' profile.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'view_profile_comments' profile.pk %}">Comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile_favorites' profile.pk %}">Favorites</a>
        </li>
    </ul>
    
    <hr>

    <div class="tab-content">        
        <!-- Comments tab -->
        {% if profile.has_comments %}
            <div class='mx-5'>
                {% for comment in profile.comment_set.all %}
                    <div class="bg-success bg-opacity-25 border border-dark rounded p-1 mx-4 my-2">
                        <div><strong>Song:</strong> <a href="{% url 'view_song' comment.song.id %}">{{comment.song.get_title}}</a> ({{comment.song.filename}}) {% include 'song_artists.html' with song=comment.song %}</div>
                        <div><strong>Posted on:</strong> {{comment.create_date|date:"F j, o"}}</div>
                        <div><strong>Rating:</strong> {{comment.rating}}/10</div>                        
                        <br>
                        {{comment.text|markdownify:"comment"}}
                    </div>
                {% endfor %}
            </div>
        {% else %}
            No comments
        {% endif %}
    </div>
{% endblock %}

homepage/templates/profile_favorites.html
{% extends 'base_page/base.html' %}
{% load markdownify %}

{% block title %}
    {{ block.super }}: {{profile.display_name}} profile
{% endblock %}

{% block content %}
    {% if user.profile and user.profile.id == profile.id %}
        <a href="{% url 'update_profile' %}">Update your profile</a>
        <br/><br/>
    {% endif %}

    <div class="fs-2">
        Profile: {{ profile.display_name }}
    </div>

    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile' profile.pk %}">Overview</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'view_profile_comments' profile.pk %}">Comments</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'view_profile_favorites' profile.pk %}">Favorites</a>
        </li>
    </ul>
    
    <hr>

    <div class="tab-content" id="myTabContent">
        <!-- Favorites tab -->
        {% for favorite in profile.favorite_set.all %}
            <li><a href="{% url 'view_song' favorite.song_id %}">{{ favorite.song.get_title }}</a></li>
        {% empty %}
            No favorites added
        {% endfor %}
    </div>
{% endblock %}

homepage/templates/update_profile.html
{% extends 'base_page/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ block.super }}: Update profile
{% endblock %}

{% block content %}
    <div class="fs-2">Editing profile</div>

    <form action="{% url 'update_profile' %}" method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class='btn btn-primary mt-2' value="Update Profile">
    </form>

    <div>
        Markdown syntax:
        <br/>
        *italic*
        <br/>
        **bold**
        <br/>
        ~~strikethrough~~
        <br/>
        ---, *** or ___ to make a horizontal line break
    </div>
{% endblock %}